export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Business Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];

export const modelFamilyList = [
  { make: "abarth", values: ['124-spider', '500'] },
  { make: "acura", values: ['ilx', 'integra', 'mdx', 'nsx', 'rdx', 'tlx'] },
  { make: "aiways", values: ['u5', 'u6'] },
  { make: "alfa-romeo", values: ['4c', 'giulia', 'giulietta', 'mito', 'stelvio-quadrifoglio', 'stelvio', 'tonale'] },
  { make: "alpine", values: ['a110'] },
  { make: "aston-martin", values: ['db11', 'dbs-superleggera', 'dbx', 'rapide', 'vanquish', 'vantage'] },
  { make: "audi", values: ['a1', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8-long', 'a8', 'e-tron-gt', 'e-tron', 'q2', 'q3', 'q4', 'q5-sportback', 'q5', 'q7', 'q8', 'r8', 'tt'] },
  { make: "bentley", values: ['bentayga', 'continental-gt', 'flying-spur', 'mulsanne'] },
  {
    make: "bmw", values: [
      "a1",
      "a3",
      "a4",
      "a5",
      "a6",
      "a7",
      "a8-long",
      "a8",
      "e-tron-gt",
      "e-tron",
      "q2",
      "q3",
      "q4",
      "q5-sportback",
      "q5",
      "q7",
      "q8",
      "r8",
      "tt"
    ]
  },
  { make: "borgward", values: ['bx3'] },
  { make: "bugatti", values: ['chiron'] },
  { make: "buick", values: ['enclave', 'encore-gx', 'envision', 'envista', 'lacrosse', 'regal'] },
  { make: "byd", values: ['atto-2', 'atto-3', 'dolphin', 'etp3', 'han', 'seal', 't3', 'tang'] },
  { make: "byton", values: ['m-byte'] },
  { make: "cadillac", values: ['celestiq', 'ct4', 'ct5', 'ct6', 'cts', 'elr', 'escalade', 'lyriq', 'xt4', 'xt5', 'xt6'] },
  { make: "changan", values: ['cs55', 'cs75', 'cs85', 'eado', 'uni-k', 'uni-t', 'uni-v'] },
  { make: "chery", values: ['arrizo-3', 'omada-5', 'tiggo-4', 'tiggo-7', 'tiggo-8'] },
  {
    make: "chevrolet", values: [
      "aveo",
      "blazer",
      "bolt",
      "camaro",
      "captiva",
      "colorado",
      "corvette",
      "cruze",
      "equinox",
      "express",
      "groove",
      "impala",
      "malibu",
      "onix",
      "orlando",
      "silverado",
      "spark",
      "suburban",
      "tahoe",
      "trailblazer",
      "traverse",
      "trax"
    ]
  },
  {
    make: "chrysler", values: [
      "300",
      "300c",
      "pacifica",
      "voyager"
    ]
  },
  {
    make: "citroen", values: [
      "ami",
      "berlingo",
      "c-elysee",
      "c-zero",
      "c1",
      "c3-aircross",
      "c3",
      "c4-cactus",
      "c4-spacetourer",
      "c4-x",
      "c4",
      "c5-aircross",
      "c5-x",
      "dispatch",
      "e-mehari",
      "grand-c4-spacetourer",
      "jumper",
      "jumpy",
      "nemo",
      "relay",
      "spacetourer"
    ]
  },
  {
    make: "cupra", values: [
      "ateca",
      "born",
      "formentor",
      "leon",
      "tavascan"
    ]
  },
  {
    make: "dacia", values: [
      "dokker",
      "duster",
      "jogger",
      "lodgy",
      "logan",
      "sandero",
      "spring"
    ]
  },
  {
    make: "dodge", values: [
      "challenger",
      "charger",
      "durango",
      "hornet"
    ]
  },
  {
    make: "dr-automobiles", values: [
      "dr-evo5",
      "dr-zero",
      "dr3"
    ]
  },
  {
    make: "ds", values: [
      "ds-3-crossback",
      "ds-3",
      "ds-4-crossback",
      "ds-4",
      "ds-5",
      "ds-7-crossback",
      "ds-7",
      "ds7",
      "ds9"
    ]
  },
  {
    make: "elaris", values: [
      "beo",
      "dyo",
      "pio"
    ]
  },
  {
    make: "fiat", values: [
      "500",
      "500l-wagon",
      "500l",
      "500x",
      "doblo-cargo",
      "doblo",
      "ducato",
      "e-ulysse",
      "fastback",
      "fiorino",
      "fullback",
      "panda",
      "pulse",
      "punto",
      "qubo",
      "scudo",
      "talento",
      "tipo",
      "toro"
    ]
  },
  { make: "fisker", values: ["ocean"] },
  {
    make: "ford", values: [
      "b-max",
      "bronco",
      "c-max",
      "ecosport",
      "edge",
      "escape",
      "everest",
      "expedition",
      "explorer",
      "f-150",
      "f-250-super-duty",
      "f-250",
      "fiesta",
      "flex",
      "focus",
      "fusion",
      "galaxy",
      "grand-tourneo-connect",
      "grand-tourneo",
      "gt",
      "ka",
      "kuga",
      "maverick",
      "mondeo",
      "mustang",
      "puma",
      "ranger",
      "s-max",
      "taurus",
      "territory",
      "tourneo-connect",
      "tourneo-courier",
      "tourneo-custom",
      "tourneo",
      "transit-connect",
      "transit-courier",
      "transit-custom",
      "transit"
    ]
  },
  { make: "gac", values: [
    "gs3",
    "gs8",
    "m8"
  ] },
  { make: "geely", values: [
    "coolray",
    "emgrand-gs",
    "emgrand",
    "galaxy-l7",
    "monjaro",
    "okavango",
    "tugella"
  ] },
  { make: "genesis", values: [
    "g70",
    "g80",
    "g90",
    "gv60",
    "gv70",
    "gv80"
  ] },
  { make: "gmc", values: [
    "acadia",
    "canyon",
    "hummer",
    "savana",
    "sierra",
    "terrain",
    "yukon"
  ] },
  { make: "gwm", values: ['ute'] },
  { make: "haval", values: [
    "dargo",
    "f7",
    "h6",
    "jolion"
  ] },
  { make: "honda", values: [
    "accord",
    "city",
    "civic",
    "clarity",
    "cr-v",
    "eny1",
    "fit",
    "honda-e",
    "honda",
    "hr-v",
    "insight",
    "jazz",
    "nsx",
    "odyssey",
    "passport",
    "pilot",
    "ridgeline"
  ] },
  { make: "hongqi", values: ["e-hs9"] },
  { make: "hyundai", values: [
    "accent",
    "azera",
    "bayon",
    "creta",
    "elantra",
    "eon",
    "genesis",
    "grandeur",
    "h-1",
    "h350",
    "i10",
    "i20",
    "i30",
    "i40",
    "ioniq-5",
    "ioniq-6",
    "ioniq",
    "ix20",
    "kona",
    "nexo",
    "palisade",
    "santa-cruz",
    "santa-fe",
    "sonata",
    "starex",
    "staria",
    "tucson",
    "veloster",
    "venue"
  ] },
  { make: "ineos", values: ["grenadier"] },
  { make: "infiniti", values: [
    "q30",
    "q50",
    "q60",
    "qx30",
    "qx50",
    "qx55",
    "qx60",
    "qx80"
  ] },
  { make: "isuzu", values: [
    "d-max",
    "mu-x",
    "n-series"
  ] },
  { make: "iveco", values: ["daily"] },
  { make: "jac", values: ["iev7s"] },
  { make: "jaguar", values: [
    "e-pace",
    "f-pace",
    "f-type",
    "i-pace",
    "xe",
    "xf",
    "xj"
  ] },
  { make: "jeep", values: [
    "avenger",
    "cherokee",
    "compass",
    "gladiator",
    "grand-cherokee",
    "grand-wagoneer",
    "recon",
    "renegade",
    "wrangler"
  ] },
  { make: "kia", values: [
    "bongo",
    "cadenza",
    "carens",
    "carnival",
    "ceed",
    "cerato",
    "ev6",
    "ev9",
    "forte",
    "k5",
    "k900",
    "mohave",
    "niro",
    "optima",
    "pegas",
    "picanto",
    "proceed",
    "rio",
    "sedona",
    "seltos",
    "sorento",
    "soul",
    "sportage",
    "stinger",
    "stonic",
    "telluride",
    "venga",
    "xceed"
  ] },
  { make: "lada", values: ["4x4"] },
  { make: "lamborghini", values: [
    "aventador",
    "countach",
    "huracan",
    "revuelto",
    "sian",
    "urus"
  ] },
  { make: "lancia", values: ["ypsilon"] },
  { make: "land-rover", values: [
    "defender",
    "discovery-sport",
    "discovery",
    "range-rover-evoque",
    "range-rover-sport",
    "range-rover-velar",
    "range-rover"
  ] },
  { make: "ldv", values: [
    "d90",
    "deliver-9",
    "g10",
    "mifa",
    "t60"
  ] },
  { make: "levc", values: ["tx", "vn5"] },
  { make: "lexus", values: [
    "ct",
    "es",
    "gx",
    "is",
    "lc",
    "ls",
    "lx",
    "nx",
    "rc",
    "rx",
    "rz",
    "ux"
  ] },
  { make: "li-auto", values: ["one"] },
  { make: "lightyear", values: ["0","one"] },
  { make: "lincoln", values: [
    "aviator",
    "continental",
    "corsair",
    "mkc",
    "mkt",
    "mkz",
    "nautilus",
    "navigator",
    "zephyr"
  ] },
  { make: "lordstown", values: ["endurance"] },
  { make: "lotus", values: [
    "eletre",
    "elise",
    "emira",
    "evija",
    "evora",
    "exige"
  ] },
  { make: "lucid", values: ["air"] },
  { make: "lynkco", values: ["01"] },
  { make: "mahindra", values: [
    "pik-up",
    "scorpio",
    "xuv700"
  ] },
  { make: "mahindra", values: [
    "pik-up",
    "scorpio",
    "xuv700"
  ] },
  { make: "man", values: ["tge"] },
  { make: "maserati", values: [
    "ghibli",
    "grancabrio",
    "granturismo",
    "grecale",
    "levante",
    "mc20",
    "quattroporte"
  ] },
  { make: "maxus", values: [
    "d60",
    "deliver-9",
    "e-deliver-3",
    "euniq5",
    "euniq6",
    "ev-80",
    "mifa-9",
    "t90"
  ] },
  { make: "mazda", values: [
    "bt-50",
    "cx-30",
    "cx-3",
    "cx-50",
    "cx-5",
    "cx-60",
    "cx-8",
    "cx-90",
    "cx-9",
    "mazda2",
    "mazda3",
    "mazda6",
    "mx-30",
    "mx-5"
  ] },
  { make: "mclaren", values: [
    "540c",
    "620r",
    "720s",
    "765lt",
    "artura",
    "gt",
    "senna"
  ] },
  { make: "mg", values: [
    "extender",
    "gs",
    "hs",
    "marvel-r",
    "mg-gt",
    "mg3",
    "mg4",
    "mg5",
    "rx5",
    "zs"
  ] },
  { make: "mini", values: [
    "clubman",
    "countryman",
    "coupe",
    "mini",
    "paceman"
  ] },
  { make: "mitsubishi", values: [
    "asx",
    "attrage",
    "eclipse-cross",
    "express",
    "fuso-canter",
    "i",
    "l200-triton-sport",
    "l200",
    "lancer-evolution",
    "mirage",
    "montero",
    "outlander",
    "pajero",
    "shogun",
    "space-star",
    "triton",
    "xpander"
  ] },
  { make: "nio", values: [
    "ec7",
    "el7",
    "es7",
    "es8",
    "et5",
    "et7"
  ] },
  { make: "nissan", values: [
    "370z",
    "altima",
    "ariya",
    "armada",
    "atlas",
    "frontier",
    "gt-r",
    "interstar",
    "juke",
    "kicks",
    "leaf",
    "magnite",
    "march",
    "maxima",
    "micra",
    "murano",
    "navara",
    "note",
    "nt400",
    "nv200",
    "nv250",
    "nv300",
    "nv400",
    "nv",
    "pathfinder",
    "patrol",
    "primastar",
    "pulsar",
    "qashqai",
    "rogue-sport",
    "rogue",
    "sakura",
    "sentra",
    "sunny",
    "titan",
    "townstar",
    "versa",
    "x-terra",
    "x-trail",
    "z"
  ] },
  { make: "opel", values: [
    "adam",
    "ampera-e",
    "astra",
    "cascada",
    "combo",
    "corsa",
    "crossland-x",
    "crossland",
    "grandland-x",
    "grandland",
    "insignia",
    "karl",
    "meriva",
    "mokka-e",
    "mokka-x",
    "mokka",
    "movano",
    "rocks-e",
    "vivaro",
    "zafira-life",
    "zafira-tourer",
    "zafira"
  ] },
  { make: "ora", values: [
    "01-cat",
    "funky",
    "funkycat"
  ] },
  { make: "peugeot", values: [
    "108",
    "2008",
    "208",
    "3008",
    "301",
    "308",
    "408",
    "5008",
    "508",
    "bipper",
    "boxer",
    "e-308",
    "expert",
    "ion",
    "landtrek",
    "partner",
    "rcz",
    "rifter",
    "traveller"
  ] },
  { make: "piaggio", values: ["porter"] },
  { make: "polestar", values: ["1", "2", "3"] },
  { make: "porsche", values: [
    "718",
    "911",
    "cayenne-coupe",
    "cayenne",
    "macan",
    "panamera",
    "taycan"
  ] },
  { make: "ram", values: [
    "1000",
    "1500",
    "3500",
    "700",
    "promaster-city",
    "promaster"
  ] },
  { make: "renault", values: [
    "5",
    "alaskan",
    "arkana",
    "austral",
    "captur",
    "clio",
    "duster",
    "espace",
    "express",
    "grand-kangoo",
    "grand-scenic",
    "kadjar",
    "kangoo-express",
    "kangoo",
    "koleos",
    "kwid",
    "master",
    "maxity",
    "megane",
    "scenic",
    "symbol",
    "taliant",
    "talisman",
    "trafic",
    "twingo",
    "twizy",
    "zoe"
  ] },
  { make: "rimac", values: ["nevera"] },
  { make: "rivian", values: ["r1s", "r1t"] },
  { make: "rolls-royce", values: [
    "boat-tail",
    "cullinan",
    "dawn",
    "ghost",
    "phantom",
    "spectre",
    "wraith"
  ] },
  { make: "saic", values: ["maxus"] },
  { make: "seat", values: [
    "alhambra",
    "altea",
    "arona",
    "ateca",
    "cupra",
    "ibiza",
    "leon",
    "mii",
    "tarraco"
  ] },
  { make: "seres", values: ["3", "5"] },
  { make: "skoda", values: [
    "citigo",
    "enyaq",
    "fabia",
    "kamiq",
    "karoq",
    "kodiaq",
    "octavia-scout",
    "octavia",
    "rapid",
    "roomster",
    "scala",
    "superb",
    "yeti"
  ] },
  { make: "smart", values: [
    "forfour",
    "fortwo",
    "one"
  ] },
  { make: "sono", values: ["sion"] },
  { make: "ssangyong", values: [
    "korando",
    "musso",
    "rexton",
    "rodius",
    "tivoli",
    "turismo",
    "xlv"
  ] },
  { make: "subaru", values: [
    "ascent",
    "brz",
    "crosstrek",
    "forester",
    "impreza",
    "legacy",
    "levorg",
    "outback",
    "solterra",
    "wrx",
    "xv-crosstrek",
    "xv"
  ] },
  { make: "suzuki", values: [
    "across",
    "baleno",
    "celerio",
    "ignis",
    "jimny",
    "s-cross",
    "swace",
    "swift",
    "sx4-s-cross",
    "vitara"
  ] },
  { make: "tesla", values: [
    "cybertruck",
    "model-3",
    "model-s",
    "model-x",
    "model-y"
  ] },
  { make: "toyota", values: [
    "4runner",
    "alphard",
    "auris",
    "avalon",
    "avanza",
    "avensis",
    "aygo-x",
    "aygo",
    "bz3",
    "bz4x",
    "c-hr",
    "camry",
    "corolla-cross",
    "corolla",
    "crown",
    "fortuner",
    "gr86",
    "granvia",
    "gt86",
    "hiace",
    "highlander",
    "hilux",
    "kluger",
    "landcruiser",
    "mirai",
    "prado",
    "previa",
    "prius-prime",
    "prius",
    "priusplus",
    "proace-city",
    "proace-verso",
    "proace",
    "rav4",
    "rush",
    "sequoia",
    "sienna",
    "supra",
    "tacoma",
    "tundra",
    "vellfire",
    "veloz",
    "venza",
    "verso",
    "yaris-cross",
    "yaris"
  ] },
  { make: "vauxhall", values: [
    "adam",
    "astra",
    "combo",
    "corsa",
    "crossland-x",
    "crossland",
    "grandland",
    "insignia",
    "meriva",
    "mokka-e",
    "mokka-x",
    "mokka",
    "movano",
    "viva",
    "vivaro",
    "zafira"
  ] },
  { make: "vinfast", values: [
    "vf6",
    "vf8",
    "vf9"
  ] },
  { make: "volkswagen", values: [
    "amarok",
    "arteon",
    "atlas",
    "beetle",
    "caddy",
    "california",
    "caravelle",
    "crafter",
    "golf",
    "grand-california",
    "id-buzz",
    "id3",
    "id4",
    "id5",
    "id6",
    "id7",
    "jetta",
    "multivan",
    "passat",
    "polo",
    "sharan",
    "t-cross",
    "t-roc",
    "taigo",
    "taos",
    "teramont",
    "tiguan-allspace",
    "tiguan",
    "touareg",
    "touran",
    "transporter",
    "up",
    "virtus"
  ] },
  { make: "volvo", values: [
    "c40",
    "ex90",
    "s60",
    "s80",
    "s90",
    "v40",
    "v60",
    "v70",
    "v90-cross-country",
    "v90",
    "xc40",
    "xc60",
    "xc70",
    "xc90"
  ] },
  { make: "wey", values: [
    "coffee-01",
    "coffee-02"
  ] },
  { make: "xpeng", values: [
    "g3",
    "g9",
    "p5",
    "p7"
  ] },
  { make: "zeekr", values: [
    "001",
    "009",
    "x"
  ] },
];